<br /><br />
<div id="view-content">
	<p>View script for controller <b>Request</b> and script/action name <b>list</b></p>
</div>





<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<link type="text/css" rel="stylesheet" href="http://dinus.org/assets/mail/mailtip.css"/>
<script type="text/javascript" src="http://dinus.org/assets/mail/jquery.mailtip.js"></script>

<br> <br><br><br><br><br><br>

<div class="container">
	<div class="row">
		<center><h2>Requests </h2></center>
                <hr>
                
        <div class="col-md-4"></div>
        <?php 
        
        for ($count = count($this->requests)-1 ; $count >= 0 ; $count--){
        ?>
        
        <div class="col-md-4">
            <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="col-md-12 row" style="padding:0px;margin-bottom:10px;">
                            
                            <div class="col-md-2">
                                <img src="http://dinus.org/img/fakultas/FIK/cs/cs.svg">
                                <div style="margin-left:30px;">
                                    <img src="<?php echo substr($this->requests[$count]['owner_photo'] , 25)?>" width="70px" height="70px" class="img-circle" style="border:3px solid #052C52;">
                                </div>
                            </div>
                            <div class="col-md-10">
                                
                                <p style="padding-left:55px;font-size:1.3em;"><strong><?php echo  $this->requests[$count]['owner_name'];  ?></strong></p>
                                <p style="padding-left:55px;font-size:1.3em;"><?php echo  $this->requests[$count]['request_time'];  ?></p>
                                <hr>
                            </div>
                            
                            <div>
                            <p>
                                <?php   echo $this->requests[$count]['desc']; ?>
                            </p>
                            </div>
                            
                            
                        </div>

                        
                        
                    </div>
                </div>

            </div>
        
        <?php } ?>

       
        </div>
	</div>
</div>

