<?php 
 if($this->user){ 
}else{
	echo "YOU ARE NOT AUTHORIZED";
}
?>
<div class="container">
<div class="row">

	<div class="col-sm-3">
		<h1>All Comments</h1> 
	</div>
	<div class="col-sm-2">
   <h4><a href="#">add Comment</a></h4> 
  </div>
</div>
<div class="table-responsive">
			<table class="table table-striped table-hover table-bordered table-condensed table-hover">
			<tr>
                <th>Comment</th>
				<th style="width:200px" width="200">Actions</th>

			</tr>

			<?php print_r($this->comments); if($this->comments) { 

			for($i=0; $i<count($this->comments); $i++){?>
				<tr id='row'>
				<td><?php echo $this->comments[$i]['comment_text']; ?></td>				
				<td>
				 <?php if($this->user->role == 'Admin' || $this->user->id == $this->comments[$i]['owner_id'] ){ ?>
				 <a href="<?php echo $this->baseUrl();?>/comment/edit?commentid=<?php echo $this->comments[$i]['comment_id']; ?>" class="text-primary" onclick="editUser('.$user_id.')" id="edit'.$user_id.'"><i class="fa fa-pencil-square-o fa-3x"></i></a>
				<a href="<?php echo $this->baseUrl();?>/comment/delete?commentid=<?php echo $this->comments[$i]['comment_id']; ?>" class="text-danger" onclick="deleteUser('.$user_id.')" id="delete'.$user_id.'"><i class="fa fa-trash-o fa-3x"></i></a>

<?php }else{
	}?>
	

				</td>	
				</tr><?php
					}
}?>
			
		</table>
		</div>
		</div>

