<!DOCTYPE html>
<html>
<head>
    <title>Conquer</title>
    <!--
    Conquer Template
    http://www.templatemo.com/tm-476-conquer
    -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="<?php echo  $this->baseUrl() ;?>/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo  $this->baseUrl() ;?>/static/css/style.css">
    <?php echo $this->headTitle() ?>
    <?php echo $this->headScript() ?>
    <?php echo $this->headStyle() ?>
</head>
<body>


<?php echo $this->render('header.phtml') ?>

<!--        <div id="nav">--><?php //echo $this->placeholder('nav') ?><!--</div>-->

<div id="content"><?php echo $this->layout()->content ?></div>

<?php echo $this->render('footer.phtml') ?>


</body>
</html>
