<br/><br/>
<div id="view-content">
    <p>View script for controller <b>Courses</b> and script/action name <b>list</b></p>
</div>
<br>
<br><br><br><br><br><br>
    <div class="container">
                <?php
                if($this->user->role == 'Admin'){ ?>
                 <a class="btn btn-primary" href="add">ADD Course</a>
<?php }?>
        <div class="page-section">
            <div class="row">
                <div class="col-md-9">
                    <div class="row" data-toggle="isotope">
                        <?php

                        for ($count = 0; $count < count($this->courses); $count++) {


                            ?>
                            <div class="item col-xs-12 col-sm-6 col-lg-4">
                                
                                <div class="panel panel-default paper-shadow" data-z="0.5">
                                    <img src="/uploads/<?php echo $this->courses[$count]['course_photo']; ?>"class="img-circle" height="60" width="60">

                                    <div class="cover overlay cover-image-full hover">
                                        <span class="img icon-block height-150 bg-default">

                                        </span>
                                        <a href="listone/id/<?php echo $this->courses[$count]['course_id']?>"
                                           class="padding-none overlay overlay-full icon-block bg-default">
                                            
                                        <span class="v-center">
                                            
                <i class="fa fa-github"></i>
            </span>
                                        </a>
                                        <a href="listone/id/<?php echo $this->courses[$count]['course_id']?>"
                                           class="overlay overlay-full overlay-hover overlay-bg-white">
                                        <span class="v-center">
                <span class="btn btn-circle btn-white btn-lg"><i class="fa fa-graduation-cap"></i></span>
                                        </span>
                                        </a>
                                    </div>
                                    <div class="panel-body">
                                        <h4 class="text-headline margin-v-0-10"><a href="listone/id/<?php echo $this->courses[$count]['course_id']?>">

                                                <?php
                                                    echo $this->courses[$count]['course_name'];
                                                ?>
                                            </a></h4>
                                        <p class="small margin-none">
                                            <span class="fa fa-fw fa-star text-yellow-800"></span>
                                            <span class="fa fa-fw fa-star text-yellow-800"></span>
                                            <span class="fa fa-fw fa-star text-yellow-800"></span>
                                            <span class="fa fa-fw fa-star-o text-yellow-800"></span>
                                            <span class="fa fa-fw fa-star-o text-yellow-800"></span>
                                        </p>
                                    </div>
                                    <hr class="margin-none"/>
                                    <div class="panel-body">

                                        <p> <?php
                                            echo substr($this->courses[$count]['course_desc'],10);
                                            ?></p>
                                        <div class="media v-middle">
                                            <div class="media-left">
                                                <img src="images/people/50/guy-4.jpg" alt="People"
                                                     class="img-circle width-40"/>
                                            </div>
                                            <div class="media-body">
                                                <h4><a href="">Adrian Demian</a>
                                                    <br/>
                                                </h4>
                                                Instructor
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?php


                        }
                        ?>
                    </div>
                    <ul class="pagination margin-top-none">
                        <li class="disabled"><a href="#">&laquo;</a></li>
                        <li class="active"><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">&raquo;</a></li>
                    </ul>
                    <br/>
                    <br/>
                </div>
                <div class="col-md-3">
                    <div class="panel panel-default" data-toggle="panel-collapse" data-open="true">
                        <div class="panel-heading panel-collapse-trigger">
                            <h4 class="panel-title">Category</h4>
                        </div>
                        <div class="panel-body list-group">
                            <ul class="list-group">
                               <?php
                                for ($count =0 ; $count < count($this->category);$count ++){
                                    
                                    ?>
                               
                                
                                <li class="list-group-item">
                                    <span class="badge pull-right"><?php echo $this->category[$count]['cat_id'] ?></span>
                                    <a class="list-group-link" href="index.html"><?php echo $this->category[$count]['cat_name']; ?></a>
                                </li>
                                
                                <?php  }?>
                            </ul>
                        </div>
                    </div>
                    
                  
                </div>
            </div>
        </div>
    </div>
    <section class="footer-section">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-3">
                    <h4 class="text-headline text-light">Corporate</h4>
                    <ul class="list-unstyled">
                        <li><a href="#">About the company</a></li>
                        <li><a href="#">Company offices</a></li>
                        <li><a href="#">Partners</a></li>
                        <li><a href="#">Terms of use</a></li>
                        <li><a href="#">Privacy</a></li>
                        <li><a href="#">Contact us</a></li>
                    </ul>
                </div>
                <div class="col-sm-6 col-md-3">
                    <h4 class="text-headline text-light">Explore</h4>
                    <ul class="list-unstyled">
                        <li><a href="">Courses</a></li>
                        <li><a href="">Tutors</a></li>
                        <li><a href="">Pricing</a></li>
                        <li><a href="">Become Tutor</a></li>
                        <li><a href="">Sign Up</a></li>
                    </ul>
                </div>
                <div class="col-xs-12 col-md-6">
                    <h4 class="text-headline text-light">Newsletter</h4>
                    <div class="form-group">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Enter email here...">
                            <span class="input-group-btn">
								<button class="btn btn-grey-800" type="button">Subscribe</button>
							  </span>
                        </div>
                    </div>
                    <br/>
                    <p>
                        <a href="#" class="btn btn-indigo-500 btn-circle"><i class="fa fa-facebook"></i></a>
                        <a href="#" class="btn btn-pink-500 btn-circle"><i class="fa fa-dribbble"></i></a>
                        <a href="#" class="btn btn-blue-500 btn-circle"><i class="fa fa-twitter"></i></a>
                        <a href="#" class="btn btn-danger btn-circle"><i class="fa fa-google-plus"></i></a>
                    </p>
                    <p class="text-subhead">
                        &copy; 2015 Learning App by mosaicpro.
                    </p>
                </div>
            </div>
        </div>
</section>
<!-- Footer -->
<footer class="footer">
    <strong>Learning</strong> v1.0.0 &copy; Copyright 2015
</footer>