<br /><br />
<div id="view-content">
	<p>View script for controller <b>Courses</b> and script/action name <b>list</b></p>
</div>
<br>
<br><br><br><br><br><br>

<?php 

if ($this->courses){
    
 
    echo '<a href="'.$this->baseUrl().'/Courses/add">  Add New Course </a>';

    
    
    
    for ($count=0 ; $count < count($this->courses) ; $count ++){
       
        
        echo '<a href= "'.$this->baseUrl().'/Courses/listone/id/'.$this->courses[$count]['course_id'].'">'. $this->courses[$count]["course_name"].' </a>';
        
        echo $this->courses[$count]['course_desc'];
            
        echo '<img src="$this->courses[$count]["course_photo"]" width="30px" height="30px">';
        
            
        echo '<a href="'.$this->baseUrl().'/Courses/delete/id/'.$this->courses[$count]['course_id'].'" class="btn btn-danger" > Delete </a>';
        
        echo '<a href="'.$this->baseUrl().'/Courses/update/id/'.$this->courses[$count]['course_id'].'" class="btn btn-success" > Edit </a>';

        
        
        echo '<br>';
        } 
    
   
    
} 


else {
    
    echo 'No course found ';
}
?>