<br /><br />
<div id="view-content">
	<p>View script for controller <b>Courses</b> and script/action name <b>listone</b></p>
</div>
<br><br><br><br>
<?php

    //print_r($this->course);

?>

<!-- Fixed navbar -->
<div class="parallax bg-white page-section">
    <div class="parallax-layer container" data-opacity="true">
        <div class="media v-middle">
            <div class="media-left">
                <span class="icon-block s60 bg-lightred"><i class="fa fa-github"></i></span>
            </div>
            <div class="media-body">

                <h1 class="text-display-1 margin-none"><?php echo $this->course[0]['course_name'];?></h1>
                <p class="small margin-none">
                    <span class="fa fa-fw fa-star text-yellow-800"></span>
                    <span class="fa fa-fw fa-star text-yellow-800"></span>
                    <span class="fa fa-fw fa-star text-yellow-800"></span>
                    <span class="fa fa-fw fa-star-o text-yellow-800"></span>
                    <span class="fa fa-fw fa-star-o text-yellow-800"></span>
                </p>
            </div>
            <div class="media-right">
                <a class="btn btn-white" href="website-directory-grid.html">Library</a>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-lg-9 col-md-8">
            <div class="page-section">
                <div class="width-350 width-300-md width-100pc-xs paragraph-inline">
                    <div class="embed-responsive embed-responsive-16by9">
                   <img src="/uploads/<?php echo $this->course[0]['course_photo']; ?>" height="200" width="200">

                    </div>
                </div>
                <h1>This Course Description</h1>
                <?php echo $this->course[0]['course_desc'];?>
                
            </div>
            
            <div class="page-section">
<?php 
 if($this->user){ 
}else{
	echo "YOU ARE NOT AUTHORIZED";
}
?>
<div class="container">
<div class="row">

	<div class="col-sm-3">
		<h1>All Matrial</h1> 
	</div>
	<div class="col-sm-2">
   <h4><a href="../../../matrial/add/cid/<?php echo $this->course[0]['course_id'];?>">add Matrial</a></h4> 
  </div>
</div>
<div class="table-responsive">
			<table style="width:800px" class="table table-striped table-hover table-bordered table-condensed table-hover">
			<tr>
                <th>Name</th>
				<th>Download</th>
				<th style="width:200px" width="100">Actions</th>

			</tr>

			<?php //print_r($this->matrialModel); 
                        if($this->matrialModel) { 

			for($i=0; $i<count($this->matrialModel); $i++){?>
				<tr id='row'>
				<td><?php echo $this->matrialModel[$i]['name']; ?></td>
				<td><?php echo $this->matrialModel[$i]['download']; ?></td>
				
				<td>
				 <?php if($this->user->role == 'Admin'){ ?>
				 <a href="edit?id=<?php echo $this->matrialModel[$i]['id']; ?>" class="text-primary" onclick="editUser('.$user_id.')" id="edit'.$user_id.'"><i class="fa fa-pencil-square-o fa-3x"></i></a>
				<a href="delete?id=<?php echo $this->matrialModel[$i]['id']; ?>" class="text-danger" onclick="deleteUser('.$user_id.')" id="delete'.$user_id.'"><i class="fa fa-trash-o fa-3x"></i></a>

<?php }else{
	}?>
				
<a href="comment?id=<?php echo $this->matrialModel[$i]['id']; ?>" class="text-danger" onclick="deleteUser('.$user_id.')" id="delete'.$user_id.'"><i class="fa fa-comments fa-3x"></i></a>




<a href="download?id=<?php echo $this->matrialModel[$i]['id']; ?>" class="text-danger" onclick="deleteUser('.$user_id.')" id="delete'.$user_id.'"><i class="fa fa-cloud-download fa-3x"></i></a>

				</td>	
				</tr><?php
					}
}?>
			
		</table>
		</div>
		</div>

                
            </div>
        </div>
        <div class="col-lg-3 col-md-4">
            <div class="page-section">
                <!-- .panel -->
                <div class="panel panel-default paper-shadow" data-z="0.5" data-hover-z="1" data-animated>
                    <div class="panel-heading">
                        <h4 class="text-headline">Course</h4>
                    </div>
                    <div class="panel-body">
                        <p class="text-caption">
                            <i class="fa fa-clock-o fa-fw"></i> 4 hrs &nbsp;
                            <i class="fa fa-calendar fa-fw"></i> <?php  echo $this->course[0]['course_date']?>
                            <br/>
                            <i class="fa fa-user fa-fw"></i> Instructor: Adrian Demian
                            <br/>
                            <i class="fa fa-mortar-board fa-fw"></i> Max. students: 50
                            <br/>
                            <i class="fa fa-check fa-fw"></i> Attending: 30
                        </p>
                    </div>
                    <hr class="margin-none" />
                    <div class="panel-body text-center">
                        <p><a class="btn btn-success btn-lg paper-shadow relative" data-z="1" data-hover-z="2" data-animated href="website-take-course.html">Start Course</a></p>
                        <p class="text-body-2">or <a href="#">buy course for $1</a></p>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">
                            <a href="#" class="text-light"><i class="fa fa-facebook fa-fw"></i> Share on facebook</a>
                        </li>
                        <li class="list-group-item">
                            <a href="#" class="text-light"><i class="fa fa-twitter fa-fw"></i> Tweet this course</a>
                        </li>
                    </ul>
                </div>
                <!-- // END .panel -->
                <!-- .panel -->
                <div class="panel panel-default paper-shadow" data-z="0.5" data-hover-z="1" data-animated>
                    <div class="panel-body">
                        <div class="media v-middle">
                            <div class="media-left">
                                <img src="images/people/110/guy-6.jpg" alt="About Adrian" width="60" class="img-circle" />
                            </div>
                            <div class="media-body">
                                <h4 class="text-title margin-none"><a href="#">Adrian Demian</a></h4>
                                <span class="caption text-light">Biography</span>
                            </div>
                        </div>
                        <br/>
                        <div class="expandable expandable-indicator-white expandable-trigger">
                            <div class="expandable-content">
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusamus aut consectetur consequatur cum cupiditate debitis doloribus, error ex explicabo harum illum minima mollitia nisi nostrum officiis omnis optio qui quisquam saepe sit sunt totam vel velit voluptatibus? Adipisci ducimus expedita id nostrum quas quia!</p>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- // END .panel -->
            </div>
            <!-- // END .page-section -->
        </div>
    </div>
</div>
<div class="bg-white page-section">
    <div class="container">
        <h4>Featured</h4>
        <div class="slick-basic slick-slider" data-items="4" data-items-lg="3" data-items-md="2" data-items-sm="1" data-items-xs="1">
            <div class="item">
                <div class="panel panel-default paper-shadow" data-z="0.5" data-hover-z="1" data-animated>
                    <div class="panel-body">
                        <div class="media media-clearfix-xs">
                            <div class="media-left">
                                <div class="cover width-90 width-100pc-xs overlay cover-image-full hover">
                                    <span class="img icon-block s90 bg-default"></span>
                                        <span class="overlay overlay-full padding-none icon-block s90 bg-default">
                        <span class="v-center">
                            <i class="fa fa-github"></i>
                        </span>
                                        </span>
                                    <a href="website-course.html" class="overlay overlay-full overlay-hover overlay-bg-white">
                                            <span class="v-center">
                            <span class="btn btn-circle btn-white btn-lg"><i class="fa fa-graduation-cap"></i></span>
                                            </span>
                                    </a>
                                </div>
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading margin-v-5-3"><a href="website-course.html">Github Webhooks for Beginners</a></h4>
                                <p class="small margin-none">
                                    <span class="fa fa-fw fa-star text-yellow-800"></span>
                                    <span class="fa fa-fw fa-star text-yellow-800"></span>
                                    <span class="fa fa-fw fa-star text-yellow-800"></span>
                                    <span class="fa fa-fw fa-star-o text-yellow-800"></span>
                                    <span class="fa fa-fw fa-star-o text-yellow-800"></span>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="panel panel-default paper-shadow" data-z="0.5" data-hover-z="1" data-animated>
                    <div class="panel-body">
                        <div class="media media-clearfix-xs">
                            <div class="media-left">
                                <div class="cover width-90 width-100pc-xs overlay cover-image-full hover">
                                    <span class="img icon-block s90 bg-primary"></span>
                                        <span class="overlay overlay-full padding-none icon-block s90 bg-primary">
                        <span class="v-center">
                            <i class="fa fa-css3"></i>
                        </span>
                                        </span>
                                    <a href="website-course.html" class="overlay overlay-full overlay-hover overlay-bg-white">
                                            <span class="v-center">
                            <span class="btn btn-circle btn-primary btn-lg"><i class="fa fa-graduation-cap"></i></span>
                                            </span>
                                    </a>
                                </div>
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading margin-v-5-3"><a href="website-course.html">Awesome CSS with LESS Processing</a></h4>
                                <p class="small margin-none">
                                    <span class="fa fa-fw fa-star text-yellow-800"></span>
                                    <span class="fa fa-fw fa-star text-yellow-800"></span>
                                    <span class="fa fa-fw fa-star text-yellow-800"></span>
                                    <span class="fa fa-fw fa-star-o text-yellow-800"></span>
                                    <span class="fa fa-fw fa-star-o text-yellow-800"></span>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="panel panel-default paper-shadow" data-z="0.5" data-hover-z="1" data-animated>
                    <div class="panel-body">
                        <div class="media media-clearfix-xs">
                            <div class="media-left">
                                <div class="cover width-90 width-100pc-xs overlay cover-image-full hover">
                                    <span class="img icon-block s90 bg-lightred"></span>
                                        <span class="overlay overlay-full padding-none icon-block s90 bg-lightred">
                        <span class="v-center">
                            <i class="fa fa-windows"></i>
                        </span>
                                        </span>
                                    <a href="website-course.html" class="overlay overlay-full overlay-hover overlay-bg-white">
                                            <span class="v-center">
                            <span class="btn btn-circle btn-red-500 btn-lg"><i class="fa fa-graduation-cap"></i></span>
                                            </span>
                                    </a>
                                </div>
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading margin-v-5-3"><a href="website-course.html">Portable Environments with Vagrant</a></h4>
                                <p class="small margin-none">
                                    <span class="fa fa-fw fa-star text-yellow-800"></span>
                                    <span class="fa fa-fw fa-star text-yellow-800"></span>
                                    <span class="fa fa-fw fa-star text-yellow-800"></span>
                                    <span class="fa fa-fw fa-star-o text-yellow-800"></span>
                                    <span class="fa fa-fw fa-star-o text-yellow-800"></span>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="panel panel-default paper-shadow" data-z="0.5" data-hover-z="1" data-animated>
                    <div class="panel-body">
                        <div class="media media-clearfix-xs">
                            <div class="media-left">
                                <div class="cover width-90 width-100pc-xs overlay cover-image-full hover">
                                    <span class="img icon-block s90 bg-brown"></span>
                                        <span class="overlay overlay-full padding-none icon-block s90 bg-brown">
                        <span class="v-center">
                            <i class="fa fa-wordpress"></i>
                        </span>
                                        </span>
                                    <a href="website-course.html" class="overlay overlay-full overlay-hover overlay-bg-white">
                                            <span class="v-center">
                            <span class="btn btn-circle btn-orange-500 btn-lg"><i class="fa fa-graduation-cap"></i></span>
                                            </span>
                                    </a>
                                </div>
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading margin-v-5-3"><a href="website-course.html">WordPress Theme Development</a></h4>
                                <p class="small margin-none">
                                    <span class="fa fa-fw fa-star text-yellow-800"></span>
                                    <span class="fa fa-fw fa-star text-yellow-800"></span>
                                    <span class="fa fa-fw fa-star text-yellow-800"></span>
                                    <span class="fa fa-fw fa-star-o text-yellow-800"></span>
                                    <span class="fa fa-fw fa-star-o text-yellow-800"></span>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="panel panel-default paper-shadow" data-z="0.5" data-hover-z="1" data-animated>
                    <div class="panel-body">
                        <div class="media media-clearfix-xs">
                            <div class="media-left">
                                <div class="cover width-90 width-100pc-xs overlay cover-image-full hover">
                                    <span class="img icon-block s90 bg-purple"></span>
                                        <span class="overlay overlay-full padding-none icon-block s90 bg-purple">
                        <span class="v-center">
                            <i class="fa fa-jsfiddle"></i>
                        </span>
                                        </span>
                                    <a href="website-course.html" class="overlay overlay-full overlay-hover overlay-bg-white">
                                            <span class="v-center">
                            <span class="btn btn-circle btn-purple-500 btn-lg"><i class="fa fa-graduation-cap"></i></span>
                                            </span>
                                    </a>
                                </div>
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading margin-v-5-3"><a href="website-course.html">Modular JavaScript with Browserify</a></h4>
                                <p class="small margin-none">
                                    <span class="fa fa-fw fa-star text-yellow-800"></span>
                                    <span class="fa fa-fw fa-star text-yellow-800"></span>
                                    <span class="fa fa-fw fa-star text-yellow-800"></span>
                                    <span class="fa fa-fw fa-star-o text-yellow-800"></span>
                                    <span class="fa fa-fw fa-star-o text-yellow-800"></span>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="panel panel-default paper-shadow" data-z="0.5" data-hover-z="1" data-animated>
                    <div class="panel-body">
                        <div class="media media-clearfix-xs">
                            <div class="media-left">
                                <div class="cover width-90 width-100pc-xs overlay cover-image-full hover">
                                    <span class="img icon-block s90 bg-default"></span>
                                        <span class="overlay overlay-full padding-none icon-block s90 bg-default">
                        <span class="v-center">
                            <i class="fa fa-cc-visa"></i>
                        </span>
                                        </span>
                                    <a href="website-course.html" class="overlay overlay-full overlay-hover overlay-bg-white">
                                            <span class="v-center">
                            <span class="btn btn-circle btn-white btn-lg"><i class="fa fa-graduation-cap"></i></span>
                                            </span>
                                    </a>
                                </div>
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading margin-v-5-3"><a href="website-course.html">Easy Online Payments with Stripe</a></h4>
                                <p class="small margin-none">
                                    <span class="fa fa-fw fa-star text-yellow-800"></span>
                                    <span class="fa fa-fw fa-star text-yellow-800"></span>
                                    <span class="fa fa-fw fa-star text-yellow-800"></span>
                                    <span class="fa fa-fw fa-star-o text-yellow-800"></span>
                                    <span class="fa fa-fw fa-star-o text-yellow-800"></span>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<section class="footer-section">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-md-3">
                <h4 class="text-headline text-light">Corporate</h4>
                <ul class="list-unstyled">
                    <li><a href="#">About the company</a></li>
                    <li><a href="#">Company offices</a></li>
                    <li><a href="#">Partners</a></li>
                    <li><a href="#">Terms of use</a></li>
                    <li><a href="#">Privacy</a></li>
                    <li><a href="#">Contact us</a></li>
                </ul>
            </div>
            <div class="col-sm-6 col-md-3">
                <h4 class="text-headline text-light">Explore</h4>
                <ul class="list-unstyled">
                    <li><a href="">Courses</a></li>
                    <li><a href="">Tutors</a></li>
                    <li><a href="">Pricing</a></li>
                    <li><a href="">Become Tutor</a></li>
                    <li><a href="">Sign Up</a></li>
                </ul>
            </div>
            <div class="col-xs-12 col-md-6">
                <h4 class="text-headline text-light">Newsletter</h4>
                <div class="form-group">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Enter email here...">
                            <span class="input-group-btn">
								<button class="btn btn-grey-800" type="button">Subscribe</button>
							  </span>
                    </div>
                </div>
                <br/>
                <p>
                    <a href="#" class="btn btn-indigo-500 btn-circle"><i class="fa fa-facebook"></i></a>
                    <a href="#" class="btn btn-pink-500 btn-circle"><i class="fa fa-dribbble"></i></a>
                    <a href="#" class="btn btn-blue-500 btn-circle"><i class="fa fa-twitter"></i></a>
                    <a href="#" class="btn btn-danger btn-circle"><i class="fa fa-google-plus"></i></a>
                </p>
                <p class="text-subhead">
                    &copy; 2015 Learning App by mosaicpro.
                </p>
            </div>
        </div>
    </div>
</section>
